
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 20 00:21:51 ICT 2020
//----------------------------------------------------

package src;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int error = 1;
  public static final int PLUS = 2;
  public static final int NUMBER = 5;
  public static final int MINUS = 3;
  public static final int TIMES = 4;
  public static final int EOF = 0;
}

